version: '3.1'

services:
  purchasing-db:
    image: postgres:11.1
    ports:
      - "4001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - beta-private_beta_network
    restart: on-failure:3

#  purchasing-java:
#    image: gpitf/purchasing
#    ports:
#      - "8220:8220"
#    depends_on:
#      - purchasing-db
#    networks:
#      - beta-private_beta_network
#    restart: on-failure:3

volumes:
  postgres-data:
    driver: local
    
networks:
  beta-private_beta_network:
    external: true
