spring.datasource.url: jdbc:postgresql://purchasing-db:5432/postgres
spring.session.store-type: none
security:
  oauth2:
    client:
      accessTokenUri: http://oidc-provider:9000/token
    resource:
      userInfoUri: http://oidc-provider:9000/me

server:
  port: 8220
  ssl:
    key-store: /keystore.jks
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: purchasing


sysparam.readOnboardingCache: true

