spring.datasource.url: jdbc:postgresql://purchasing-db:5432/postgres
spring.session.store-type: none
security:
  oauth2:
    client:
      clientId: DaiZSffyCYac6MOrL9WKUprxsqk6hjCX
      clientSecret: wMhH8OiSkfW51v8dFSuf_RzDWCztaJGhoVl-0xfZvHT1Vz-Nd8lFU-r_36pMi2vh
      accessTokenUri: https://nigel-m.eu.auth0.com/oauth/token
      userAuthorizationUri: https://nigel-m.eu.auth0.com/authorize
      scope: openid email
    resource:
      userInfoUri: https://nigel-m.eu.auth0.com/userinfo
    sso:
      login-path: /login

server:
  port: 8220
  ssl:
    key-store: /keystore.jks
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: purchasing


sysparam.readOnboardingCache: true

