spring:
  application:
    name: gpitf-purchasing
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#    generate-dll: false
#    hibernate.ddl-auto: none
  #    show-sql: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

onboarding.api.url: http://localhost:5100
spring.jackson.serialization.write-dates-as-timestamps: false

server.servlet.session.timeout: 3600s # Session timeout. If a duration suffix is not specified, seconds will be used.
server.port: 8220

spring.session.store-type: none

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: catalogue-private-beta-ci
      clientSecret: ptjqjbxbdxryshjbsqelfwoonibgnnee
      accessTokenUri: http://localhost:9000/token
      userAuthorizationUri: http://localhost:9000/auth
      #      tokenName: oauth_token
      #      authenticationScheme: query
      #      clientAuthenticationScheme: form
      scope: openid email
    resource:
      userInfoUri: http://localhost:9000/me
    sso:
      login-path: /login

#show sql statement
logging.level.org.hibernate.SQL: debug
logging.level.org.springframework: info

#show sql values
#logging.level.org.hibernate.type.descriptor.sql: trace
logging.level.uk.nhs.gpitf.purchasing: INFO

#management.endpoints.web.exposure.include: loggers
#endpoints.loggers.sensitive: false


management:
  endpoints:
    web:
      exposure:
        include: loggers
      base-path: /
      path-mapping:
        loggers: /loggers


sysparam.shortlist.max: 4
sysparam.directaward.maxvalue: 20000
sysparam.writeOnboardingCache: false    ## Default false. Set to true to write to  resources/onboardingCache json files
sysparam.readOnboardingCache: false     ## Default false. Set to true to read from resources/onboardingCache json files

